package br.com.datarich.investordata.models.enums;

public enum Sector {
    FINANCIAL, AIRLINE, REALSTATE, ENERGY_GENERATION ,ENERGY_TRANSMISSION, ENERGY_DISTRIBUTION, AUTOMOTIVE, TOURISM, FOOD, INDUSTRIAL, COMMUNICATIONS, RETAIL, OIL, GAS, FUEL, HEALTHCARE, IT, PUBLIC, COMMODITIES
}
